### ISSUE TITLE
Support variables in backend configuration

### ISSUE THREAD

**Issue by raymondbutcher** [raymondbutcher/ltf#1]
# Proposed idea

Feature:
* Dynamic backends:
  * Allow use of variables in backend configuration blocks.

LTF solves the [issue](https://github.com/hashicorp/terraform/issues/13022) of Terraform not supporting input variables in the backend configuration block. Note that LTF only adds support for input variables. It does not support accessing local values, nor data sources.

When LTF runs, it does the following:

* Reads the backend block from the Terraform configuration.
* Renders the backend block using HCL using Terraform variables.
* Passes each line from the rendered backend block to Terraform using the -backend-config= command line argument, which takes precedence over the values in the file.

# Work required

* Parse configuration
* Load tfvars like Terraform does (parse files, understand CLI arguments involving variables, understand environment variables like `TF_CLI_ARGS_plan=-var-file` and `TF_VAR_name=value`)
* Render HCL
* Pass `-backend-config` args.

This seems feasible because it's written in Go and we have access to the Terraform source code. It's also feasible in Python, Pretf does all of this. It might be difficult in other languages.

**Comment by ivandir** [comment]
C'mon guys this issue of dynamic backends based on workspace_key_prefix being ties to the workspace variable has been in discussion since [Mar 23, 2017](https://github.com/hashicorp/terraform/issues/13022#issue-216556166)

How are we supposed to be using workspaces if we can't isolate the backends for each workspace?

**Comment by raymondbutcher** [comment]
For anyone that comes across this issue: LTF now has support for variables in `*.tfbackend` files. It's not quite the same as putting variables directly in the backend definition in the `*.tf` file, but it's pretty close and achieves the same thing.

You create any empty or partial backend definition in your Terraform configuration:

```
# backend.tf

terraform {
  backend "local" {}
}
```

And create a `*.tfbackend` file with the details:

```
# config.local.tfbackend

path = "/tmp/terraform/${var.env}${var.color == "" ? "" : ".${var.color}"}.tfstate"
```

Then when LTF runs it will automatically find the `*.tfbackend` file, render it with variables, then pass it to the Terraform command like this:

```
terraform init -backend-config=path=/tmp/terraform/dev.tfstate
```
